// Score thresholds — must match backend shortlist/config.py
export const SCORE_VISIBLE = 75;
export const SCORE_STRONG = 85;

// Country/region options for LinkedIn location targeting.
// Regions expand to multi-country searches server-side.
// Must stay in sync with REGION_COUNTRIES in shortlist/collectors/linkedin.py.
export const COUNTRIES = [
  { value: "", label: "United States (default)" },
  // ── Regions ──
  { value: "Europe", label: "🌍 Europe",
    description: "United Kingdom, Germany, France, Netherlands, Switzerland, Ireland, Spain, Poland, Italy, Sweden" },
  { value: "European Union", label: "🇪🇺 European Union",
    description: "Germany, France, Netherlands, Spain, Ireland, Poland, Italy, Belgium, Austria, Portugal" },
  { value: "DACH", label: "🏔️ DACH",
    description: "Germany, Austria, Switzerland" },
  { value: "Scandinavia", label: "❄️ Scandinavia",
    description: "Denmark, Norway, Sweden, Finland" },
  { value: "APAC", label: "🌏 Asia-Pacific",
    description: "India, Singapore, Australia, Japan, South Korea, Hong Kong, New Zealand" },
  { value: "LATAM", label: "🌎 Latin America",
    description: "Brazil, Mexico, Argentina, Colombia, Chile, Peru" },
  // ── Countries ──
  { value: "United States", label: "🇺🇸 United States" },
  { value: "United Kingdom", label: "🇬🇧 United Kingdom" },
  { value: "Canada", label: "🇨🇦 Canada" },
  { value: "Germany", label: "🇩🇪 Germany" },
  { value: "India", label: "🇮🇳 India" },
  { value: "Australia", label: "🇦🇺 Australia" },
  { value: "France", label: "🇫🇷 France" },
  { value: "Netherlands", label: "🇳🇱 Netherlands" },
  { value: "Ireland", label: "🇮🇪 Ireland" },
  { value: "Singapore", label: "🇸🇬 Singapore" },
  { value: "Switzerland", label: "🇨🇭 Switzerland" },
  { value: "Sweden", label: "🇸🇪 Sweden" },
  { value: "Spain", label: "🇪🇸 Spain" },
  { value: "Israel", label: "🇮🇱 Israel" },
  { value: "Japan", label: "🇯🇵 Japan" },
  // ── rest of world, alphabetical ──
  { value: "Argentina", label: "🇦🇷 Argentina" },
  { value: "Austria", label: "🇦🇹 Austria" },
  { value: "Belgium", label: "🇧🇪 Belgium" },
  { value: "Brazil", label: "🇧🇷 Brazil" },
  { value: "Chile", label: "🇨🇱 Chile" },
  { value: "China", label: "🇨🇳 China" },
  { value: "Colombia", label: "🇨🇴 Colombia" },
  { value: "Czech Republic", label: "🇨🇿 Czech Republic" },
  { value: "Denmark", label: "🇩🇰 Denmark" },
  { value: "Egypt", label: "🇪🇬 Egypt" },
  { value: "Estonia", label: "🇪🇪 Estonia" },
  { value: "Finland", label: "🇫🇮 Finland" },
  { value: "Greece", label: "🇬🇷 Greece" },
  { value: "Hong Kong", label: "🇭🇰 Hong Kong" },
  { value: "Hungary", label: "🇭🇺 Hungary" },
  { value: "Indonesia", label: "🇮🇩 Indonesia" },
  { value: "Italy", label: "🇮🇹 Italy" },
  { value: "Kenya", label: "🇰🇪 Kenya" },
  { value: "Lithuania", label: "🇱🇹 Lithuania" },
  { value: "Luxembourg", label: "🇱🇺 Luxembourg" },
  { value: "Malaysia", label: "🇲🇾 Malaysia" },
  { value: "Mexico", label: "🇲🇽 Mexico" },
  { value: "New Zealand", label: "🇳🇿 New Zealand" },
  { value: "Nigeria", label: "🇳🇬 Nigeria" },
  { value: "Norway", label: "🇳🇴 Norway" },
  { value: "Pakistan", label: "🇵🇰 Pakistan" },
  { value: "Peru", label: "🇵🇪 Peru" },
  { value: "Philippines", label: "🇵🇭 Philippines" },
  { value: "Poland", label: "🇵🇱 Poland" },
  { value: "Portugal", label: "🇵🇹 Portugal" },
  { value: "Romania", label: "🇷🇴 Romania" },
  { value: "Saudi Arabia", label: "🇸🇦 Saudi Arabia" },
  { value: "South Africa", label: "🇿🇦 South Africa" },
  { value: "South Korea", label: "🇰🇷 South Korea" },
  { value: "Taiwan", label: "🇹🇼 Taiwan" },
  { value: "Thailand", label: "🇹🇭 Thailand" },
  { value: "Turkey", label: "🇹🇷 Turkey" },
  { value: "Ukraine", label: "🇺🇦 Ukraine" },
  { value: "United Arab Emirates", label: "🇦🇪 United Arab Emirates" },
  { value: "Vietnam", label: "🇻🇳 Vietnam" },
];

export const CURRENCIES = [
  { value: "USD", label: "USD", symbol: "$" },
  { value: "GBP", label: "GBP", symbol: "£" },
  { value: "EUR", label: "EUR", symbol: "€" },
  { value: "CAD", label: "CAD", symbol: "CA$" },
  { value: "AUD", label: "AUD", symbol: "A$" },
  { value: "INR", label: "INR", symbol: "₹" },
  { value: "SGD", label: "SGD", symbol: "S$" },
  { value: "CHF", label: "CHF", symbol: "CHF" },
  { value: "SEK", label: "SEK", symbol: "kr" },
  { value: "JPY", label: "JPY", symbol: "¥" },
  { value: "ILS", label: "ILS", symbol: "₪" },
] as const;
