import Link from "next/link";

export const metadata = {
  title: "How salary estimates work — Shortlist",
  description: "How Shortlist estimates salaries for job listings that don't include pay.",
};

export default function SalaryEstimatesPage() {
  return (
    <div className="mx-auto max-w-[900px] px-6 pt-16 pb-24">
      {/* Back link */}
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-900 transition-colors mb-12"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
        </svg>
        Back to jobs
      </Link>

      {/* Header */}
      <div className="mb-12">
        <p className="font-mono text-xs tracking-widest uppercase text-emerald-600 mb-4">Salary transparency</p>
        <h1 className="text-3xl md:text-4xl font-bold tracking-tighter text-gray-900">
          How salary estimates work
        </h1>
        <p className="mt-4 text-base text-gray-500 leading-relaxed max-w-[60ch]">
          Most job listings don&apos;t include salary. Shortlist fills the gap
          with AI estimates — but you should know exactly what they&apos;re based on.
        </p>
      </div>

      {/* Sections */}
      <div className="divide-y divide-gray-200/60">
        {/* Listed vs estimated */}
        <div className="py-8">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">Listed vs. estimated</h2>
          <p className="text-base text-gray-600 leading-relaxed max-w-[65ch]">
            When a listing includes a salary range, Shortlist shows it exactly as posted — bold, no prefix.
            When a listing doesn&apos;t include pay, Shortlist shows an AI estimate prefixed with a tilde (~)
            and a dotted underline. These are two different things. The visual difference is intentional.
          </p>
        </div>

        {/* What the AI knows */}
        <div className="py-8">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">What the AI knows</h2>
          <p className="text-base text-gray-600 leading-relaxed max-w-[65ch]">
            Estimates are generated by Gemini 2.0 Flash using three inputs: the job title, the company name,
            and the location. Gemini draws on its training data — which includes compensation surveys, job
            listings, and public salary data indexed before its knowledge cutoff.
          </p>
          <p className="mt-3 text-base text-gray-600 leading-relaxed max-w-[65ch]">
            For well-known companies with standard roles in major markets, estimates tend to land in the
            right ballpark. The AI has seen a lot of software job data.
          </p>
        </div>

        {/* What it doesn't know */}
        <div className="py-8">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">What it doesn&apos;t know</h2>
          <p className="text-base text-gray-600 leading-relaxed max-w-[65ch]">
            Estimates don&apos;t reflect equity, bonuses, or total compensation — only base salary.
            They don&apos;t account for the specific team budget, recent funding, or internal pay bands
            that the hiring manager knows and you don&apos;t. Estimates for early-stage startups,
            niche roles, or non-US markets are less reliable. The AI has no visibility into
            what this specific company is actually willing to pay right now.
          </p>
        </div>

        {/* Confidence */}
        <div className="py-8">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">Confidence</h2>
          <p className="text-base text-gray-600 leading-relaxed max-w-[65ch]">
            Shortlist asks the AI to self-assess its confidence: low, medium, or high.
            High confidence typically means the role is common and the company is well-documented.
            Low confidence usually means the role is unusual, the company is small or obscure,
            or the location has limited comparable data.
          </p>
          <p className="mt-3 text-base text-gray-600 leading-relaxed max-w-[65ch]">
            Confidence is AI self-reported and imperfect. A &quot;high confidence&quot; estimate can still
            be wrong. Treat it as a rough signal, not a guarantee.
          </p>
        </div>

        {/* Why we show estimates anyway */}
        <div className="py-8">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">Why we show estimates anyway</h2>
          <p className="text-base text-gray-600 leading-relaxed max-w-[65ch]">
            Salary is one of the most useful filters in a job search, and most postings hide it.
            A rough estimate — clearly labeled as such — is more useful than nothing when you&apos;re
            deciding whether a role is worth pursuing. You already know the posting is silent on pay;
            having a directional signal lets you prioritize triage.
          </p>
          <p className="mt-3 text-base text-gray-600 leading-relaxed max-w-[65ch]">
            We&apos;re not trying to anchor you to a number. We&apos;re trying to help you spend your
            time on roles that are likely in your range. Always verify in the actual conversation.
          </p>
        </div>
      </div>

      {/* Footer note */}
      <p className="mt-12 font-mono text-xs text-gray-400">
        Questions or corrections? Reach out at{" "}
        <a href="mailto:smadam9@gmail.com" className="underline underline-offset-2 hover:text-gray-600 transition-colors">
          smadam9@gmail.com
        </a>
      </p>
    </div>
  );
}
