"""Tests for shortlist.aww_crypto — cross-language decryption and grant loading."""
import base64
import json
import os
import tempfile
import time

import pytest
import nacl.signing
import nacl.public
import nacl.secret
from nacl.encoding import RawEncoder

from shortlist.aww_crypto import load_grant, sign_pull_request, decrypt_slice, verify_signature


# --- Test vectors (generated by Go crypto package / scripts/generate_test_vectors.py) ---
# These match the vectors in internal/crypto/interop_test.go

# From scripts/generate_test_vectors.py output:
# Ed25519 key pair (seed = first 32 bytes of private key)
ED25519_SEED_HEX = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60"
ED25519_PUB_HEX = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa3f4a18446b0b8d183f8e3"


class TestLoadGrant:
    def test_from_json_string(self):
        grant_json = json.dumps({
            "private_key": "dGVzdC1wcml2YXRlLWtleQ==",
            "owner_public_key": "dGVzdC1vd25lci1rZXk=",
            "node_id": "abc123def456",
            "slice_name": "networking",
            "server_url": "https://example.com",
        })
        grant = load_grant(grant_json)
        assert grant is not None
        assert grant["node_id"] == "abc123def456"
        assert grant["slice_name"] == "networking"

    def test_from_file(self):
        grant_data = {
            "private_key": "dGVzdC1wcml2YXRlLWtleQ==",
            "owner_public_key": "dGVzdC1vd25lci1rZXk=",
            "node_id": "abc123def456",
            "slice_name": "networking",
            "server_url": "https://example.com",
        }
        with tempfile.NamedTemporaryFile(mode="w", suffix=".key", delete=False) as f:
            json.dump(grant_data, f)
            path = f.name
        try:
            grant = load_grant(path)
            assert grant is not None
            assert grant["node_id"] == "abc123def456"
        finally:
            os.unlink(path)

    def test_from_env_json(self, monkeypatch):
        grant_json = json.dumps({
            "private_key": "a2V5",
            "owner_public_key": "b3duZXI=",
            "node_id": "aabbccddeeff",
            "slice_name": "networking",
            "server_url": "https://example.com",
        })
        monkeypatch.setenv("AWW_GRANT_JSON", grant_json)
        grant = load_grant()
        assert grant is not None
        assert grant["node_id"] == "aabbccddeeff"

    def test_from_env_file(self, monkeypatch):
        grant_data = {
            "private_key": "a2V5",
            "owner_public_key": "b3duZXI=",
            "node_id": "112233445566",
            "slice_name": "networking",
            "server_url": "https://example.com",
        }
        with tempfile.NamedTemporaryFile(mode="w", suffix=".key", delete=False) as f:
            json.dump(grant_data, f)
            path = f.name
        try:
            monkeypatch.setenv("AWW_GRANT_FILE", path)
            grant = load_grant()
            assert grant is not None
            assert grant["node_id"] == "112233445566"
        finally:
            os.unlink(path)

    def test_missing_field(self):
        grant_json = json.dumps({"private_key": "a2V5"})  # missing other fields
        assert load_grant(grant_json) is None

    def test_invalid_json(self):
        assert load_grant("not json") is None

    def test_no_source(self):
        # No env vars set, no source
        assert load_grant() is None


class TestSignPullRequest:
    def test_produces_valid_signature(self):
        """Generate a key pair, sign, and verify the signature."""
        signing_key = nacl.signing.SigningKey.generate()
        priv_b64 = base64.b64encode(
            signing_key.encode() + signing_key.verify_key.encode()
        ).decode()

        pub_b64, sig_b64, timestamp = sign_pull_request(
            priv_b64, "abc123def456", "networking"
        )

        # Verify signature
        message = f"GET abc123def456/networking {timestamp}"
        pub_bytes = base64.b64decode(pub_b64)
        sig_bytes = base64.b64decode(sig_b64)
        verify_key = nacl.signing.VerifyKey(pub_bytes)
        verify_key.verify(message.encode(), sig_bytes)  # raises if invalid

    def test_timestamp_is_recent(self):
        signing_key = nacl.signing.SigningKey.generate()
        priv_b64 = base64.b64encode(
            signing_key.encode() + signing_key.verify_key.encode()
        ).decode()

        _, _, timestamp = sign_pull_request(priv_b64, "abc123def456", "networking")
        assert abs(int(timestamp) - int(time.time())) < 2


class TestDecryptSlice:
    """Full encrypt-then-decrypt round-trip using PyNaCl directly,
    simulating what the Go server produces."""

    def _make_encrypted_slice(self):
        """Create an encrypted slice the same way Go does:
        nacl/secretbox for content, nacl/box for key wrap."""
        # Generate keys
        owner_signing = nacl.signing.SigningKey.generate()
        owner_verify = owner_signing.verify_key
        consumer_signing = nacl.signing.SigningKey.generate()
        consumer_verify = consumer_signing.verify_key

        # Content key
        content_key = nacl.utils.random(32)

        # Encrypt content with nacl/secretbox
        # Go format: nonce (24) || ciphertext
        # PyNaCl encrypt(msg, nonce, RawEncoder) returns nonce || ciphertext already
        plaintext = b"# Test Professional\n\n## About\nA test slice for decryption."
        secret_box = nacl.secret.SecretBox(content_key)
        content_nonce = nacl.utils.random(24)
        encrypted_content = secret_box.encrypt(
            plaintext, content_nonce, encoder=RawEncoder
        )  # returns nonce + ciphertext

        # Wrap content key with nacl/box (owner → consumer)
        # Go format: nonce (24) || box-encrypted content key
        owner_x25519 = owner_signing.to_curve25519_private_key()
        consumer_x25519_pub = consumer_verify.to_curve25519_public_key()
        box = nacl.public.Box(owner_x25519, consumer_x25519_pub)
        wrap_nonce = nacl.utils.random(24)
        wrapped_key = box.encrypt(
            content_key, wrap_nonce, encoder=RawEncoder
        )  # returns nonce + ciphertext

        # Sign plaintext
        signed = owner_signing.sign(plaintext)
        signature = signed.signature

        return {
            "plaintext": plaintext.decode(),
            "encrypted_content_b64": base64.b64encode(encrypted_content).decode(),
            "key_wrap_b64": base64.b64encode(wrapped_key).decode(),
            "consumer_priv_b64": base64.b64encode(
                consumer_signing.encode() + consumer_verify.encode()
            ).decode(),
            "owner_pub_b64": base64.b64encode(owner_verify.encode()).decode(),
            "signature_b64": base64.b64encode(signature).decode(),
        }

    def test_round_trip(self):
        data = self._make_encrypted_slice()
        decrypted = decrypt_slice(
            encrypted_content_b64=data["encrypted_content_b64"],
            key_wrap_b64=data["key_wrap_b64"],
            consumer_private_key_b64=data["consumer_priv_b64"],
            owner_public_key_pinned_b64=data["owner_pub_b64"],
            owner_public_key_from_server_b64=data["owner_pub_b64"],
        )
        assert decrypted == data["plaintext"]

    def test_owner_key_mismatch_raises(self):
        data = self._make_encrypted_slice()
        # Use a different owner key for the server response
        other_key = nacl.signing.SigningKey.generate()
        other_pub_b64 = base64.b64encode(other_key.verify_key.encode()).decode()

        with pytest.raises(ValueError, match="Owner public key mismatch"):
            decrypt_slice(
                encrypted_content_b64=data["encrypted_content_b64"],
                key_wrap_b64=data["key_wrap_b64"],
                consumer_private_key_b64=data["consumer_priv_b64"],
                owner_public_key_pinned_b64=data["owner_pub_b64"],
                owner_public_key_from_server_b64=other_pub_b64,
            )

    def test_wrong_consumer_key_fails(self):
        data = self._make_encrypted_slice()
        # Use a different consumer key
        wrong_key = nacl.signing.SigningKey.generate()
        wrong_priv_b64 = base64.b64encode(
            wrong_key.encode() + wrong_key.verify_key.encode()
        ).decode()

        with pytest.raises(Exception):  # nacl.exceptions.CryptoError
            decrypt_slice(
                encrypted_content_b64=data["encrypted_content_b64"],
                key_wrap_b64=data["key_wrap_b64"],
                consumer_private_key_b64=wrong_priv_b64,
                owner_public_key_pinned_b64=data["owner_pub_b64"],
                owner_public_key_from_server_b64=data["owner_pub_b64"],
            )

    def test_tampered_content_fails(self):
        data = self._make_encrypted_slice()
        # Flip a byte in the encrypted content
        enc = bytearray(base64.b64decode(data["encrypted_content_b64"]))
        enc[-1] ^= 0xFF
        tampered_b64 = base64.b64encode(bytes(enc)).decode()

        with pytest.raises(Exception):
            decrypt_slice(
                encrypted_content_b64=tampered_b64,
                key_wrap_b64=data["key_wrap_b64"],
                consumer_private_key_b64=data["consumer_priv_b64"],
                owner_public_key_pinned_b64=data["owner_pub_b64"],
                owner_public_key_from_server_b64=data["owner_pub_b64"],
            )


class TestVerifySignature:
    def test_valid_signature(self):
        signing_key = nacl.signing.SigningKey.generate()
        plaintext = "# Hello World"
        signed = signing_key.sign(plaintext.encode())
        sig_b64 = base64.b64encode(signed.signature).decode()
        pub_b64 = base64.b64encode(signing_key.verify_key.encode()).decode()

        assert verify_signature(plaintext, sig_b64, pub_b64) is True

    def test_invalid_signature(self):
        signing_key = nacl.signing.SigningKey.generate()
        other_key = nacl.signing.SigningKey.generate()
        plaintext = "# Hello World"
        signed = other_key.sign(plaintext.encode())
        sig_b64 = base64.b64encode(signed.signature).decode()
        pub_b64 = base64.b64encode(signing_key.verify_key.encode()).decode()

        assert verify_signature(plaintext, sig_b64, pub_b64) is False

    def test_tampered_plaintext(self):
        signing_key = nacl.signing.SigningKey.generate()
        plaintext = "# Hello World"
        signed = signing_key.sign(plaintext.encode())
        sig_b64 = base64.b64encode(signed.signature).decode()
        pub_b64 = base64.b64encode(signing_key.verify_key.encode()).decode()

        assert verify_signature("# Tampered", sig_b64, pub_b64) is False
